services:
  dns-helper:
    image: ghcr.io/auspex/container-dns-helper:latest
    container_name: dns-helper
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/run/dbus:/var/run/dbus
    network_mode: host
 